CREATE TABLE Clients
(
	Id BIGINT PRIMARY KEY NOT NULL IDENTITY,
	FirstName VARCHAR (50) NOT NULL,
	LastName VARCHAR (50) NOT NULL,
	BirthDate SMALLDATETIME NOT NULL,
	Email VARCHAR (50) NOT NULL,
	UserName NVARCHAR (50) NOT NULL UNIQUE,
	Pass NVARCHAR (50) NOT NULL
);

CREATE TABLE Products
(
	Id BIGINT PRIMARY KEY NOT NULL IDENTITY,
	OwnerId BIGINT NOT NULL REFERENCES Clients(Id),
	UserId BIGINT REFERENCES Clients(Id),
	Title NVARCHAR (50) NOT NULL,
	ShortDescription NVARCHAR (500) NOT NULL,
	LongDescription NVARCHAR (4000) NOT NULL,
	DateCard SMALLDATETIME NOT NULL,
	DateBay SMALLDATETIME,
	Price DECIMAL(18,0) NOT NULL,
	Picture1 VARBINARY (MAX),
	Picture2 VARBINARY (MAX),
	Picture3 VARBINARY (MAX),
	Sold INT NOT NULL
);

select * from Products